### ISSUE TITLE
is there options to accept vector input

### ISSUE THREAD

**Issue by Charvelau** [berndporr/iir1#9]
Dear Dr. Porr,

I need to process some force and torque information for robot, and your work is of great help. Thank you very much for that. But there is still one issue, cause each sensor got 6 output, so currently, I need to define multiple different low pass filters for them, even with same order, cutting off frequency and also sampling ratio, so I am wondering if IIR1 supports vector input, cause failed when doing so, which will be of great ease.
Sincerely,

Qingwei Liu, AIST, Japan

**Comment by berndporr** [comment]
Just create a standard C++ array of the filter classes (i.e Bandpass** bandpass). Initialise them in a loop with the same parameters and then process them in a loop. You can write your own class for processing arrays which basically is just loops. Since data can be represented in different ways it's up to you to write a wrapper class for your purposes. Bottomline: there are no plans to do this.
